# lef conversion program by Seijiro Moriyama (May 13, 2018)
# rev. 2 (Aug 2, 2019)
# works only for ones generated by ALSI Yamdada-san
require 'byebug'

$direction={}
cell = nil
lef_cells = []
File.read(File.join(File.dirname(__FILE__),'./OR1_stdcells.lib')).each_line{|l|
#  puts l
  if l=~/cell\((\S+)\)/
    cell = $1
    $direction[cell]={}
    lef_cells << cell
  elsif l=~/pin\((\S+)\).*direction: *(\S+);/
#    puts $1, $2
    $direction[cell][$1] = $2.upcase
  end
}
# debugger

def read_lef lines
  pl = nil 
  cell = nil
  pin = nil 
  ports = {}
  flag_pin = false
  width = nil
  layer = nil
  lines.each_line{|l|
    if flag_pin
      if pl=~/USE SIGNAL/ 
        puts "    USE SIGNAL ;\n"
      elsif pl =~ /LAYER (\S+)/
        layer = $1
        ports[layer] = []
      elsif pl=~/(PATH|POLYGON)[^;]*$/
          ports[layer] << pl.chomp + l.strip.sub(/  ;$/, ' ;') + "\n"
          l = nil
      elsif pl=~/(RECT |PATH |POLYGON )/
        ports[layer] << pl.sub(/  ;$/, ' ;')
      elsif pl=~/WIDTH +(\S+)/
        ports[layer] << pl.sub(/  ;$/, ' ;')
      elsif pl=~ /PORT/
      # do nothing
      elsif pl=~/END *#{pin}/
        puts '    PORT'
        ports.each_pair{|layer, geoms|
          puts "      LAYER #{layer} ;"
          geoms.each{|g|
            puts g
          }
        }
        puts '    END'
        ports = {}
        puts pl
        flag_pin = false
      elsif pl=~ /END/       # do nothing
      else
        puts pl.sub(/  ;$/, ' ;') if pl       
      end
    elsif pl=~/MACRO *(\S+)/
      cell = $1
      puts pl
    elsif pl=~/PIN *(\S+)/
      pin = $1 
      puts pl
      # puts "cell:#{cell}, pin:#{pin}"
      dir = $direction[cell][pin] || 'INOUT' # for vdd, gnd, etc. 
      puts "    DIRECTION #{dir} ;" if dir
      flag_pin = true
    else
      puts pl if pl
    end
    pl = l
  }
  puts pl
end

def extract_macro name, lines 
  result = nil
  lines.each_line{|l|
    if result
      result << l
      break if l=~/END +#{name}/
    elsif l =~ /MACRO +#{name}/
      result = l
    end
  }
  result
end

if ARGV[0].nil?
  lines =<<EOF
    PORT
      LAYER ML1 ;
        WIDTH 1.000 ;
        PATH 4.800 20.500 4.800 18.000 ;
    END
EOF
  
  puts path_to_rect(lines)
  
  debugger
  
  lines =<<EOF
    PORT
      LAYER ML1 ;
        WIDTH 1.000 ;
        PATH 4.800 20.500 4.800 18.000 7.500 18.000 7.500 6.500 6.800 6.500 6.800 3.800 ;
    END
EOF
  
  puts path_to_rect(lines)
  
  debugger
end

if File.directory? ARGV[0]
  merged = File.join(File.dirname(__FILE__), File.basename(ARGV[0])+'_merged.lef')
  File.open(merged, 'w'){|f|
    lef_cells.each{|lef|
      lines = File.read(File.join ARGV[0], lef+'.lef')
      lines = extract_macro lef, lines
      read_lef lines
      f.puts lines
    }
  }
#  puts "'#{merged}' created"
else
  lines = File.read(ARGV[0])
#  lines = extract_macro 'an21', lines
  read_lef lines
end
